config/routes.rb
Rails.application.routes.draw do
  
  resources :small_groups
  resources :comments, only: [:create, :destroy]

  get 'board/content1'
  get 'board/content2'
  get 'board/sorry'
  get 'board/manual'
  get 'board/manual1'
  get 'board/manual2'
  get 'board/manual3'
  get 'board/manual4'
  get 'board/staff'
  get 'board/event'
  get 'board/investigation'

  resources :club_meetings
  resources :meetings
  
  get '/club/member_management'
  get '/meetings/:id' => 'meetings#show'
  
  get 'ect/repairing_page'

  resources :video, except: [:show]
  post '/video/create/:club_id' => 'video#create'
  get '/video/index' => 'video#index' # 내용물 확인을 위해 '결' 씀
  get '/video/club_video/:club_id' => 'video#club_video'
  root 'front#index'
  
  get 'apply_content/create'
  
  get '/video/:id' => 'video#destroy'

  devise_for :users
  devise_scope :user do 
    get '/users/sign_out' , to: 'devise/sessions#destroy'
    get '/users/:id/edit' , to: 'users#edit'
    patch '/users/:id', to: 'users#update'
  end
  resources :users, only: [:new, :create, :edit, :update]
  
  
  get 'club/appliable_club'
  
  get 'club/my_club'
  
  get 'club/option_change/:club_id' => 'club#option_change'
  
  get 'club/club_members'
  
  get 'club/delete_club_member/:club_member_id' => 'club#delete_club_member'
  
  get 'club/add_club_member/:club_id/:user_id' => 'club#add_club_member'
  
  get 'club/edit_club/:club_id' => 'club#edit_club'
  
  post 'club/update_club/:club_id' => 'club#update_club'
  
  get 'club/delete_club/:club_id' => 'club#delete_club'
  
  get 'club/new_club'
  
  post 'club/create_club'
  
  
  
  

  get 'small_groups/appliable_club'
  
  get 'small_groups/my_group'
  
  get 'small_groups/option_change/:small_group_id' => 'small_groups#option_change'
  
  get 'small_groups/1/group_members' => 'small_groups#group_members'
  
  get 'small_groups/delete_group_member/:group_member_id' => 'small_groups#delete_group_member'
  
  get 'small_groups/add_group_member/:small_group_id/:user_id' => 'small_groups#add_group_member'
  

  
  get 'club/index'
  
  get 'club/club_view/:club_id' => 'club#club_view'
  
  
  get 'apply_form/index'
  get 's_apply_form/index'
  
  get 'apply_form/new'
  get 's_apply_form/new'
  
  post 'apply_form/create/:club_id' => 'apply_form#create'
  post 's_apply_form/create/:small_group_id' => 's_apply_form#create'
  
  get 'apply_form/edit/:club_id' => 'apply_form#edit'
  get 's_apply_form/edit/:small_group_id' => 's_apply_form#edit'
  
  post 'apply_form/update/:club_id' => 'apply_form#update'
  post 's_apply_form/update/:small_group_id' => 's_apply_form#update'
  
  get 'apply_content/index' # 동아리 관리자, 서버 관리자는 지원한 사람들의 목록과 지원서 내용을 볼 수 있다.
  get 's_apply_content/index'
  
  get 'apply_content/index_backup'
  
  get 'apply_content/user_application_view/:apply_content_id' => 'apply_content#user_application_view' # 지원한 내용을 보는 뷰
  get 's_apply_content/user_application_view/:apply_content_id' => 's_apply_content#user_application_view'
  
  get 'apply_content/user_application_list' # 일반 유저가 지원한 동아리들의 목록을 볼 수 있는 페이지
  get 's_apply_content/user_application_list' 
  
  get 'apply_content/new/:club_id' => 'apply_content#new'
  get 's_apply_content/new/:small_group_id' => 's_apply_content#new'
  
  post 'apply_content/create/:apply_form_id/:user_id' => 'apply_content#create'
  post 's_apply_content/create/:s_apply_form_id/:user_id' => 's_apply_content#create'
  
  get 'apply_content/edit/:apply_content_id' => 'apply_content#edit'
  get 's_apply_content/edit/:s_apply_content_id' => 's_apply_content#edit'
  
  post 'apply_content/update/:apply_content_id' => 'apply_content#update'
  post 's_apply_content/update/:s_apply_content_id' => 's_apply_content#update'
  
  get 'apply_content/destroy/:apply_content_id' => 'apply_content#destroy'
  get 's_apply_content/destroy/:s_apply_content_id' => 's_apply_content#destroy'
  
  get 'users/index' 
  
  get 'front/index'
  
  get 'front/try'
  
  get 'post/index' => 'post#index'
  
  get 'post/club_index/:post_id' => 'post#club_index'
  
  get 'post/new' => 'post#new'
  
  post 'post/create/:club_id' => 'post#create'
  
  get 'post/edit/:post_id' => 'post#edit'
  
  post 'post/update/:post_id' => 'post#update'
  
  get 'post/destroy/:post_id' => 'post#destroy'
  
  get 'ect/repairing_page' => 'ext#repairing_page'

end

app/models/meeting.rb
class Meeting < ApplicationRecord
    belongs_to :club
    belongs_to :user
    

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]

  # GET /meetings
  # GET /meetings.json
  def index
    @users = User.all
    @meetings = Meeting.all
    @clubs = Club.all
    # @meetings = Meeting.where(club_id: params[:club_id])
    # if user_signed_in?
    #   @current_check_club = ClubMember.find_by_user_id(current_user.id)
    # end    
  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meetings = Meeting.all
    @clubs = ClubMember.all
    
    @meeting = Meeting.find_by(id: params[:id])

  end

  # GET /meetings/new
  def new
    
      # @club_id = ClubMember.find_by_user_id(current_user.id).club_id
      @meeting = Meeting.new
      # @clubs=Club.all
      @clubs = Club.all
      
    
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @club = Club.find_by(params[:club_id])
    @meeting = Meeting.new(meeting_params )
    @meeting.user_id = current_user.id
    @meeting.club_id = @club.id
    
    
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to  @meeting, notice: 'Meeting was successfully created.' }
        format.json { render :show, status: :created, location: @meeting }
      else
        format.html { render :new }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meetings/1
  # PATCH/PUT /meetings/1.json
  def update
    respond_to do |format|
      if @meeting.update(meeting_params)
        format.html { redirect_to  @meeting, notice: 'Meeting was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting }
      else
        format.html { render :edit }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting.destroy
    respond_to do |format|
      format.html { redirect_to meetings_url, notice: 'Meeting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end
    
    # def set_club

    # end
    # def set_club
    #   @club_id = Club.find(params[:club_id])
    # end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_params
      params.require(:meeting).permit(:name, :content, :club_id, :user_id, :start_time, :end_time)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(meeting) do |f| %>
  <% if meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% meeting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :제목 %>
    <%= f.text_field :name %>
  </div>

  <div class="field mt60">
    <%= f.label :내용 %>
    <%= f.text_area :content %>
  </div>
  



  <div class="field">
    <%= f.label :시작시간 %>
    <div class="ml40"><%= f.datetime_select :start_time , {:class => "selc"}%></div>
  </div>

  <div class="field ">
    <%= f.label :끝나는시간 %>
    <div class="ml40"><%= f.datetime_select :end_time %></div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<p style="margin: 4rem">edit</p>

<h1>Editing Meeting</h1>

<%= render 'form', meeting: @meeting %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<div class="calendar-index-body">
  <div class="container">
    <div>
       <div class="calendar-index-title align-center"><p>슼쳌 달력</p></div>
       <% if user_signed_in? %>
           <% if current_user.authorization == '1' || current_user.authorization == '0' %>
              <div class="align-right"><%= link_to '일정등록', new_meeting_path ,{:class => "calendar-index-new-btn" }%></div>
           <% end %>
        <%end%>  
        
          <%= month_calendar events: @meetings do |date, meetings| %>
            <div class="calendar-index-day-body">
              <p style="font-weight: bold; font-size: 1.2rem"><%= date.day %></p>
              <% meetings.each do |meeting| %>
                
                  <ul>
                      <% @clubs.each do |c| %>
                        <% if meeting.club_id == c.id %>
                          <a href="meetings/<%=meeting.id%>"><li class="calendar-index-li"><p class="overflow-hddn" style="height: 25px; width: 120px; font-weight: bold; color: #315293"><%= meeting.name %></p><p class="align-right overflow-hddn" style="padding-left: 1rem; color: #fbb50f; font-size: 0.8rem;">-<%=c.club_name%></p></li></a>
                          <div class="dropdown-divider"></div>
                        <%end%>
                      <%end%>
                  </ul>    
                
              <% end %>
            </div>  
          <% end %>
        
    </div>
  </div>
</div>

app/views/meetings/new.html.erb
<div class="calendar-show mh700">
    <div class="container">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="calendar-new">
                    <h1>새로운 일정 등록</h1>
                    
                    <%= render 'form', meeting: @meeting %>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
    </div>
</div>

app/views/meetings/show.html.erb
<div class="calendar-show mh700">
  <div class="container">
    <div class="row">
      <div  class="col-3"></div>
      <div  class="col-6">
        <div class="align-center calendar-show-body">
          <div>
            <p class="calendar-show-title"><%= @meeting.name %></p>
          </div>
          <div>
            <p>- <%= @meeting.club.club_name %> -</p>

          </div>

          <div class="calendar-show-day">
            <p class="calendar-show-day-p"  align="left">시작일</p>
            <p class="calendar-show-day-s"><%= @meeting.start_time %></p>
          </div>
          
          <div class="calendar-show-day">
            <p class="calendar-show-day-p"align="left">종료일</p>
            <p class="calendar-show-day-s"> <%= @meeting.end_time %></p>
          </div>
          <div class="dropdown-divider"></div>
          <div>
            <p style="font-weight: bold; font-size: 1.2rem; padding: 1rem;">내용</p>
            <div class="calendar-show-box align-left"><%= @meeting.content %></div>
          </div>
          
          <div class="align-center">
            
            <div class=""><%= link_to '목록', meetings_path ,{:class => "calendar-show-bttn-1"} %></div>
            <% if @meeting.user_id == current_user.id  %>
              <div class="calendar-show-bttn-2 align-center"><%= link_to '삭제', meeting_path, method: :delete, data: { confirm: '삭제하시겠습니까?'}%></div>
            <% end %>
          </div>
        </div>   
      </div>
      <div  class="col-3"></div>
    </div>
  </div>
</div>