config/routes.rb
Rails.application.routes.draw do
  
  resources :small_groups
  resources :comments, only: [:create, :destroy]

  get 'board/content1'
  get 'board/content2'
  get 'board/sorry'
  get 'board/manual'
  get 'board/manual1'
  get 'board/manual2'
  get 'board/manual3'
  get 'board/manual4'
  get 'board/staff'
  get 'board/event'
  get 'board/investigation'

  resources :club_meetings
  resources :meetings
  
  get '/club/member_management'
  get '/meetings/:id' => 'meetings#show'
  
  get 'ect/repairing_page'

  resources :video, except: [:show]
  post '/video/create/:club_id' => 'video#create'
  get '/video/index' => 'video#index' # 내용물 확인을 위해 '결' 씀
  get '/video/club_video/:club_id' => 'video#club_video'
  root 'front#index'
  
  get 'apply_content/create'
  
  get '/video/:id' => 'video#destroy'

  devise_for :users
  devise_scope :user do 
    get '/users/sign_out' , to: 'devise/sessions#destroy'
    get '/users/:id/edit' , to: 'users#edit'
    patch '/users/:id', to: 'users#update'
  end
  resources :users, only: [:new, :create, :edit, :update]
  
  
  get 'club/appliable_club'
  
  get 'club/my_club'
  
  get 'club/option_change/:club_id' => 'club#option_change'
  
  get 'club/club_members'
  
  get 'club/delete_club_member/:club_member_id' => 'club#delete_club_member'
  
  get 'club/add_club_member/:club_id/:user_id' => 'club#add_club_member'
  
  get 'club/edit_club/:club_id' => 'club#edit_club'
  
  post 'club/update_club/:club_id' => 'club#update_club'
  
  get 'club/delete_club/:club_id' => 'club#delete_club'
  
  get 'club/new_club'
  
  post 'club/create_club'
  
  
  
  

  get 'small_groups/appliable_club'
  
  get 'small_groups/my_group'
  
  get 'small_groups/option_change/:small_group_id' => 'small_groups#option_change'
  
  get 'small_groups/1/group_members' => 'small_groups#group_members'
  
  get 'small_groups/delete_group_member/:group_member_id' => 'small_groups#delete_group_member'
  
  get 'small_groups/add_group_member/:small_group_id/:user_id' => 'small_groups#add_group_member'
  

  
  get 'club/index'
  
  get 'club/club_view/:club_id' => 'club#club_view'
  
  
  get 'apply_form/index'
  get 's_apply_form/index'
  
  get 'apply_form/new'
  get 's_apply_form/new'
  
  post 'apply_form/create/:club_id' => 'apply_form#create'
  post 's_apply_form/create/:small_group_id' => 's_apply_form#create'
  
  get 'apply_form/edit/:club_id' => 'apply_form#edit'
  get 's_apply_form/edit/:small_group_id' => 's_apply_form#edit'
  
  post 'apply_form/update/:club_id' => 'apply_form#update'
  post 's_apply_form/update/:small_group_id' => 's_apply_form#update'
  
  get 'apply_content/index' # 동아리 관리자, 서버 관리자는 지원한 사람들의 목록과 지원서 내용을 볼 수 있다.
  get 's_apply_content/index'
  
  get 'apply_content/index_backup'
  
  get 'apply_content/user_application_view/:apply_content_id' => 'apply_content#user_application_view' # 지원한 내용을 보는 뷰
  get 's_apply_content/user_application_view/:apply_content_id' => 's_apply_content#user_application_view'
  
  get 'apply_content/user_application_list' # 일반 유저가 지원한 동아리들의 목록을 볼 수 있는 페이지
  get 's_apply_content/user_application_list' 
  
  get 'apply_content/new/:club_id' => 'apply_content#new'
  get 's_apply_content/new/:small_group_id' => 's_apply_content#new'
  
  post 'apply_content/create/:apply_form_id/:user_id' => 'apply_content#create'
  post 's_apply_content/create/:s_apply_form_id/:user_id' => 's_apply_content#create'
  
  get 'apply_content/edit/:apply_content_id' => 'apply_content#edit'
  get 's_apply_content/edit/:s_apply_content_id' => 's_apply_content#edit'
  
  post 'apply_content/update/:apply_content_id' => 'apply_content#update'
  post 's_apply_content/update/:s_apply_content_id' => 's_apply_content#update'
  
  get 'apply_content/destroy/:apply_content_id' => 'apply_content#destroy'
  get 's_apply_content/destroy/:s_apply_content_id' => 's_apply_content#destroy'
  
  get 'users/index' 
  
  get 'front/index'
  
  get 'front/try'
  
  get 'post/index' => 'post#index'
  
  get 'post/club_index/:post_id' => 'post#club_index'
  
  get 'post/new' => 'post#new'
  
  post 'post/create/:club_id' => 'post#create'
  
  get 'post/edit/:post_id' => 'post#edit'
  
  post 'post/update/:post_id' => 'post#update'
  
  get 'post/destroy/:post_id' => 'post#destroy'
  
  get 'ect/repairing_page' => 'ext#repairing_page'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_nested_set :scope => [:commentable_id, :commentable_type]

  validates :body, :presence => true
  validates :user, :presence => true

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_votable

  belongs_to :commentable, :polymorphic => true

  # NOTE: Comments belong to a user
  belongs_to :user

  # Helper class method that allows you to build a comment
  # by passing a commentable object, a user_id, and comment text
  # example in readme
  def self.build_from(obj, user_id, comment)
    new \
      :commentable => obj,
      :body        => comment,
      :user_id     => user_id
  end

  #helper method to check if a comment has children
  def has_children?
    self.children.any?
  end

  # Helper class method to lookup all comments assigned
  # to all commentable types for a given user.
  scope :find_comments_by_user, lambda { |user|
    where(:user_id => user.id).order('created_at DESC')
  }

  # Helper class method to look up all comments for
  # commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |commentable_str, commentable_id|
    where(:commentable_type => commentable_str.to_s, :commentable_id => commentable_id).order('created_at DESC')
  }

  # Helper class method to look up a commentable object
  # given the commentable class name and id
  def self.find_commentable(commentable_str, commentable_id)
    commentable_str.constantize.find(commentable_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        commentable = commentable_type.constantize.find(commentable_id)
        @comment = Comment.build_from(commentable, current_user.id, body)
        @comment.name = params[:comment][:name]
        
        respond_to do |format|
            if @comment.save
                make_child_comment
                format.html {redirect_to(request.referrer, :notice => '댓글이 작성되었습니다.')}
            else
                format.html {redirect_to(request.referrer, :alert => '댓글 내용을 작성해주세요.')}
            end
        end
    end
    
    def destroy
        @comment = Comment.find_by(id: params[:id])
        if @comment.user_id == current_user.id
            @comment.delete
            respond_to do |format|
                format.html { redirect_to(request.referrer, :notice => '댓글이 삭제되었습니다.')}
                format.js
            end
        else
            respond_to do |format|
                format.html { redirect_to(request.referrer, :alert => '댓글을 삭제할 수 없습니다.')}
            end
        end
    end
    
    private
    
    def comment_params
        params[:comment][:name] = current_user.name
        params.require(:comment).permit(:body, :commentable_id, :commentable_type, :comment_id, :user_id, :name)
    end
    
    def commentable_type
        comment_params[:commentable_type]
    end
    
    def commentable_id
        comment_params[:commentable_id]
    end
    
    def comment_id
        comment_params[:comment_id]
    end
    
    def body
        comment_params[:body]
    end
    
    def make_child_comment
        return "" if comment_id.blank?
        
        parent_comment = Comment.find comment_id
        @comment.move_to_child_of(parent_comment)
    end
end
    
    
    
    
    
    
    
    
    

app/views/comments/_form.html.erb
<%= form_for @new_comment do |f| %>  
    <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
    <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
    <div class="row">
        <div class="col-10">
            <div class="field form-group">
                <%= f.text_area :body, class: 'form-control comment-form' %>
            </div>
        </div>
        <div class="col-2">
            <div class="field form-group">
                <%= submit_tag "입력",  {:class => "btn comment-form-btn"} %><br/>
            </div>
        </div>
    </div>
<% end %>

app/views/comments/_reply.html.erb
<% comments.each do |comment| %>  
    <div class="comments-show" id="comment<%= comment.id %>">
        <div class="comment">
            <div class="row">
                <div class="col-1"><img src="/assets/user-img/person<%= (comment.user.id)%15 %>.png" style="width: 1.5rem;"></div>
                <div class="col-9">
                    <div class="comment-reply-user"><%= comment.user != nil ? comment.user.name : comment.name %></div> 
                    <%= content_tag(:div, comment.body, {:class => "comment-reply-content"}) %>
                    <div class="comment-reply-time"><%= time_ago_in_words(comment.created_at) %>전</div>
                    
                </div>
                
                <div class="col-2 mt20">
                    <%= link_to "지우기", comment_path(comment), method: :delete, remote: false, data: { confirm: "정말로 지우시겠습니까?" }, style: "color: red; font-weight: bold;padding: 0.3rem 0.5rem; color: red; font-weight: bold;" %>
                    <div class="comment-reply-btn">
                        <a  class="comment-reply-btn-2" onclick="showHide('comment_reply_<%= comment.id %>')" onfocus="this.blur()">대댓글</a>
                    </div>
                </div>
                
                        
            </div>
            
            
            
            <div id="comment_reply_<%= comment.id %>" style="display:none;">
                <div class="reply-form">
                    <%= form_for @new_comment do |f| %>
                        <%= f.hidden_field :commentable_id, value: @new_comment.commentable_id %>
                        <%= f.hidden_field :commentable_type, value: @new_comment.commentable_type %>
                        <%= f.hidden_field :comment_id, value: comment.id %>
                        <div class="row">
                            <div class="col-2"></div>
                            <div class="col-8">
                                <div class="field form-group">
                                <%= f.text_area :body, class: 'form-control comment-form' %>
                                </div>
                            </div>
                            <div class="col-2">
                                 <div class="field form-group" style="margin-bottom: 60px">
                                    <%= submit_tag "입력", {:class => "btn comment-form-btn"} %>
                                 </div>
                            </div>
                        </div>
                       
                        
                    <% end %>
                </div>
            </div>
        </div>
        <div style="margin-left: 100px;">
            <%= render partial: "comments/reply_end", locals: {comments: comment.children} %>
        </div>
    </div>
    <hr/>
<% end %>

app/views/comments/_reply_end.html.erb
<% comments.each do |comment| %>  
    <div class="comments-show">
        <div class="comment">
            <div class="row">
                <div class="col-1"><img src="/assets/user-img/person<%= (comment.user.id)%15 %>.png" style="width: 1.5rem;"></div>
                <div class="col-9">
                    <div class="comment-reply-user"><%= comment.user != nil ? comment.user.name : comment.name %></div> 
                    <%= content_tag(:div, comment.body, {:class => "comment-reply-content"}) %>
                    <div class="comment-reply-time"><%= time_ago_in_words(comment.created_at) %>전</div>
                    
                </div>
                <div class="col-2 mt35">
                    <%= link_to "지우기", comment_path(comment), method: :delete, remote: false, data: { confirm: "정말로 지우시겠습니까?" }, style: "color: red; font-weight: bold;padding: 0.3rem 0.5rem; color: red; font-weight: bold;" %>
                    
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/comments/_template.html.erb
<div class="dropdown-divider mt30 mb30"></div>
<div class="comments-header">  
    <h4 class="comment-h4">댓글 (<%= commentable.comment_threads.count %>)</h4>
</div>
<%= render partial: "comments/form", locals: {new_comment: new_comment} %>
<div class="comments-container">  
    <%= render partial: "comments/reply", locals: {comments: commentable.root_comments} %>
</div>