config/routes.rb
Rails.application.routes.draw do
  
  resources :small_groups
  resources :comments, only: [:create, :destroy]

  get 'board/content1'
  get 'board/content2'
  get 'board/sorry'
  get 'board/manual'
  get 'board/manual1'
  get 'board/manual2'
  get 'board/manual3'
  get 'board/manual4'
  get 'board/staff'
  get 'board/event'
  get 'board/investigation'

  resources :club_meetings
  resources :meetings
  
  get '/club/member_management'
  get '/meetings/:id' => 'meetings#show'
  
  get 'ect/repairing_page'

  resources :video, except: [:show]
  post '/video/create/:club_id' => 'video#create'
  get '/video/index' => 'video#index' # 내용물 확인을 위해 '결' 씀
  get '/video/club_video/:club_id' => 'video#club_video'
  root 'front#index'
  
  get 'apply_content/create'
  
  get '/video/:id' => 'video#destroy'

  devise_for :users
  devise_scope :user do 
    get '/users/sign_out' , to: 'devise/sessions#destroy'
    get '/users/:id/edit' , to: 'users#edit'
    patch '/users/:id', to: 'users#update'
  end
  resources :users, only: [:new, :create, :edit, :update]
  
  
  get 'club/appliable_club'
  
  get 'club/my_club'
  
  get 'club/option_change/:club_id' => 'club#option_change'
  
  get 'club/club_members'
  
  get 'club/delete_club_member/:club_member_id' => 'club#delete_club_member'
  
  get 'club/add_club_member/:club_id/:user_id' => 'club#add_club_member'
  
  get 'club/edit_club/:club_id' => 'club#edit_club'
  
  post 'club/update_club/:club_id' => 'club#update_club'
  
  get 'club/delete_club/:club_id' => 'club#delete_club'
  
  get 'club/new_club'
  
  post 'club/create_club'
  
  
  
  

  get 'small_groups/appliable_club'
  
  get 'small_groups/my_group'
  
  get 'small_groups/option_change/:small_group_id' => 'small_groups#option_change'
  
  get 'small_groups/1/group_members' => 'small_groups#group_members'
  
  get 'small_groups/delete_group_member/:group_member_id' => 'small_groups#delete_group_member'
  
  get 'small_groups/add_group_member/:small_group_id/:user_id' => 'small_groups#add_group_member'
  

  
  get 'club/index'
  
  get 'club/club_view/:club_id' => 'club#club_view'
  
  
  get 'apply_form/index'
  get 's_apply_form/index'
  
  get 'apply_form/new'
  get 's_apply_form/new'
  
  post 'apply_form/create/:club_id' => 'apply_form#create'
  post 's_apply_form/create/:small_group_id' => 's_apply_form#create'
  
  get 'apply_form/edit/:club_id' => 'apply_form#edit'
  get 's_apply_form/edit/:small_group_id' => 's_apply_form#edit'
  
  post 'apply_form/update/:club_id' => 'apply_form#update'
  post 's_apply_form/update/:small_group_id' => 's_apply_form#update'
  
  get 'apply_content/index' # 동아리 관리자, 서버 관리자는 지원한 사람들의 목록과 지원서 내용을 볼 수 있다.
  get 's_apply_content/index'
  
  get 'apply_content/index_backup'
  
  get 'apply_content/user_application_view/:apply_content_id' => 'apply_content#user_application_view' # 지원한 내용을 보는 뷰
  get 's_apply_content/user_application_view/:apply_content_id' => 's_apply_content#user_application_view'
  
  get 'apply_content/user_application_list' # 일반 유저가 지원한 동아리들의 목록을 볼 수 있는 페이지
  get 's_apply_content/user_application_list' 
  
  get 'apply_content/new/:club_id' => 'apply_content#new'
  get 's_apply_content/new/:small_group_id' => 's_apply_content#new'
  
  post 'apply_content/create/:apply_form_id/:user_id' => 'apply_content#create'
  post 's_apply_content/create/:s_apply_form_id/:user_id' => 's_apply_content#create'
  
  get 'apply_content/edit/:apply_content_id' => 'apply_content#edit'
  get 's_apply_content/edit/:s_apply_content_id' => 's_apply_content#edit'
  
  post 'apply_content/update/:apply_content_id' => 'apply_content#update'
  post 's_apply_content/update/:s_apply_content_id' => 's_apply_content#update'
  
  get 'apply_content/destroy/:apply_content_id' => 'apply_content#destroy'
  get 's_apply_content/destroy/:s_apply_content_id' => 's_apply_content#destroy'
  
  get 'users/index' 
  
  get 'front/index'
  
  get 'front/try'
  
  get 'post/index' => 'post#index'
  
  get 'post/club_index/:post_id' => 'post#club_index'
  
  get 'post/new' => 'post#new'
  
  post 'post/create/:club_id' => 'post#create'
  
  get 'post/edit/:post_id' => 'post#edit'
  
  post 'post/update/:post_id' => 'post#update'
  
  get 'post/destroy/:post_id' => 'post#destroy'
  
  get 'ect/repairing_page' => 'ext#repairing_page'

end

app/models/small_group.rb
class SmallGroup < ApplicationRecord
    has_many :group_members
    has_many :users
    has_one :group_option
    
    
    mount_uploader :img_url, ImguploaderUploader
acts_as_commentable
end

app/controllers/small_groups_controller.rb
class SmallGroupsController < ApplicationController
  before_action :set_small_group, only: [:show, :edit, :update, :destroy]

  # GET /small_groups
  # GET /small_groups.json
  def index
    @small_groups = SmallGroup.all
    puts @small_groups.count
    
    
    
  end

  # GET /small_groups/1
  # GET /small_groups/1.json
  def show
    @small_group = SmallGroup.find(params[:id])
    @new_comment = Comment.build_from(@small_group, current_user.id, "")
    
    @members = GroupMember.all
    if user_signed_in?
      @current_check_group = GroupMember.find_by_small_group_id(@small_group.id) && GroupMember.find_by_user_id(current_user.id) 
    end
    # puts @current_check_club.club_id
    # 보고있는 클럽의 옵션테이블을 확인하는 테이블을 저장.
    @current_check_option = GroupOption.find_by_small_group_id(@small_group.id)    
  end

  # GET /small_groups/new
  def new
    @small_group = SmallGroup.new
  end

  # GET /small_groups/1/edit
  def edit
  end

  # POST /small_groups
  # POST /small_groups.json
  def create
    
    
    @small_group = SmallGroup.new(small_group_params)
    @small_group.user_id = current_user.id

    respond_to do |format|
      if @small_group.save
        @option = GroupOption.new
        @option.small_group_id = @small_group.id
        @option.apply_active = "0"
        @option.view_active = "0"
            
        @option.save
            
        @member = GroupMember.new
        @member.user_id = current_user.id
        @member.small_group_id = @small_group.id
        @member.save
        if current_user.authorization =='2'
            current_user.authorization = '4'
        end
        current_user.save
        format.html { redirect_to @small_group, notice: '' }
        format.json { render :show, status: :created, location: @small_group }
      else
        format.html { render :new }
        format.json { render json: @small_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /small_groups/1
  # PATCH/PUT /small_groups/1.json
  def update
    respond_to do |format|
      if @small_group.update(small_group_params)
        
        format.html { redirect_to @small_group, notice: '' }
        format.json { render :show, status: :ok, location: @small_group }
      else
        format.html { render :edit }
        format.json { render json: @small_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /small_groups/1
  # DELETE /small_groups/1.json
  def destroy
    @small_group.destroy
    respond_to do |format|
      format.html { redirect_to small_groups_url, notice: '' }
      format.json { head :no_content }
    end
  end

  def add_group_member # 클럽 멤버를 추가하는 함수
    if user_signed_in? && current_user.authorization != '4' &&
      # 클럽 멤버에 존재하지 않은 경우만 추가
      ClubMember.where(club_id: params[:small_group_id], user_id: params[:user_id]).exists? == false
      
      @member = GroupMember.new
      @member.user_id = params[:user_id]
      @member.club_id = params[:small_group_id]
      @member.save
    end
    redirect_to '/s_apply_content/index'
  end

  def delete_group_member # 클럽 멤버를 지우는 함수
    if user_signed_in?
      @member = GroupMember.find(params[:group_member_id])
      # 현재 로그인 한 유저가 서버관리자 이거나 지우는 유저의 클럽아이디가 로그인하고 있는 클럽아이디가 같고 단체 관리자이면 멤버를 삭제할수있다.
      if current_user.authorization == '0' || current_user.authorization == '4'
        # if ClubMember.find_by(:user_id => current_user.id, :use)
        @member.destroy
        
        redirect_to '/small_groups/club_members'
      else
        redirect_to '/small_groups/'
      end
    end
  end

  def group_members
    @small_groups = SmallGroup.all
    if user_signed_in? && current_user.authorization == '0' || current_user.authorization == '4'
      @members = GroupMember.all
      @group_check = GroupMember.find_by_user_id(current_user.id)
    else
      redirect_to '/small_groups/'
    end
  end
  
  def option_change
    @option = GroupOption.find_by_small_group_id(params[:small_group_id])
    
    if user_signed_in?
      if current_user.authorization == "0"
        # apply_active가 "0"이면 "1"로 바꾼다.
        if @option.apply_active == "0"
          @option.apply_active = "1"
        # 반대
        else
          @option.apply_active = "0"
        end
        
        @option.save
        redirect_to '/small_groups/' + @option.small_group_id.to_s
      elsif current_user.authorization == "4"
        # 현재 로그인 한 유저가 보고있는 클럽에 속해있는지 확인하는 함수
        @check_in_group = GroupMember.find_by_user_id(current_user.id)
        # 만약 로그인 한 유저의 클럽이 보고있는 클럽과 다를경우
        if @check_in_group.small_group_id != params[:small_group_id].to_i
          redirect_to '/small_groups/'
        else
          # apply_active가 "0"이면 "1"로 바꾼다.
          if @option.apply_active == "0"
            @option.apply_active = "1"
          # 반대
          else
            @option.apply_active = "0"
          end
          
          @option.save
          redirect_to '/small_groups/' + @option.small_group_id.to_s
        
        end
      else
        redirect_to '/small_groups/'
      end
    end
  end
  
  def appliable_club
    @groups = GroupOption.all
    # 옵션테이블에 활성화된 테이블을 찾는 함수
    @group_check = GroupOption.find_by_apply_active('1')
    @group_check2 = GroupOption.find_by_view_active('1')
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_small_group
      @small_group = SmallGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def small_group_params
      
      params.require(:small_group).permit(:group_name, :introduce, :content, :img_url, :user_id)
    end
end

app/helpers/small_group_helper.rb
module SmallGroupHelper
end

app/helpers/small_groups_helper.rb
module SmallGroupsHelper
end

app/views/small_groups/_form.html.erb
<%= form_for(small_group) do |f| %>
  <% if small_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(small_group.errors.count, "error") %> prohibited this small_group from being saved:</h2>

      <ul>
      <% small_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field small-groups-create-input">
    <%= f.label :"모임명", {:class => "small-groups-create-p"} %>
    <div><%= f.text_field :group_name, {:class => ""} %></div>
  </div>
  
  <div class="field small-groups-create-input">
    <%= f.label :"이미지", {:class => "small-groups-create-p"} %>
    <div><%= f.file_field :img_url,  {:class => ""}%></div>
  </div>
  
  <div class="field small-groups-create-input">
    <%= f.label :"짧은 소개", {:class => "small-groups-create-p"} %>
    <div><%= f.text_field :introduce, {:class => ""} %></div>
  </div>
  
  <div class="field small-groups-create-input">
    <%= f.label :"상세 내용", {:class => "small-groups-create-p"} %>
    <div><%= f.text_area :content , {:class => ""}%></div>
  </div>
  
  
  
  <div class="actions align-center">
    
    <%= f.submit :"소모임 만들기" %>
  </div>
<% end %>

app/views/small_groups/edit.html.erb
<p style="margin: 10rem;">뷰2</p>

<div class="clubs-index mt60 mb60">

<h1>Editing Small Group</h1>

<%= render 'form', small_group: @small_group %>

<%= link_to 'Show', @small_group %> |
<%= link_to 'Back', small_groups_path %>

</div>

app/views/small_groups/group_members.html.erb
<div class="club-members-index">
  <div class="container mt60 mb60">
    <div class="row mt60">
      <div class="col">
        <% if current_user.authorization == '0' %>
          <div class="align-center"><div class="clubmember-title">전체 회원 목록</div></div>
          <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">이름</th>
                <th scope="col">전화번호</th>
                <th scope="col">이메일</th>
                <th scope="col">학번</th>
                <th scope="col">학과</th>
                <th scope="col">학년</th>
                <th scope="col">소속 단체</th>
                <th scope="col"></th>
              </tr>
            </thead>
            <% @members.each do |x| %>
            <tbody>
              <tr>
                <th scope="row"> </th>
                <td><%= x.user.name %></td>
                <td><%= x.user.phone_number %></td>
                <td><%= x.user.mail %></td>
                <td><%= x.user.email %></td>
                <td><%= x.user.department.department_name %></td>
                <td><%= x.user.grade_id %></td>
                <td><%= x.small_group.group_name %></td>
                <td><a id="" href = "/small_groups/delete_group_member/<%= x.id %>">삭제</a></td>
              </tr>
            </tbody>
          <% end %>
          </table>
        <% elsif current_user.authorization == '4' %>
       
          <div class="align-center"><div class="clubmember-title"><%= GroupMember.find_by_user_id(current_user.id).small_group.group_name %> 회원 목록</div></div>
          <table class="table table-striped">
            <thead class="thead-dark">
              <tr>
                <th scope="col">#</th>
                <th scope="col">이름</th>
                <th scope="col">전화번호</th>
                <th scope="col">이메일</th>
                <th scope="col">학번</th>
                <th scope="col">학과</th>
                <th scope="col">학년</th>
                <th scope="col"></th>
              </tr>
            </thead>
          <% @members.each do |x| %>
            <% if @group_check.small_group_id == x.small_group_id %>
              <tbody>
                <tr>
                  <th scope="col"> </th>
                  <td><%= x.user.name %></td>
                  <td><%= x.user.phone_number %></td>
                  <td><%= x.user.mail %></td>
                  <td><%= x.user.email %></td>
                  <td><%= x.user.department.department_name %></td>
                  <td><%= x.user.grade_id %> </td>
                  <td><a id="" href = "/small_groups/delete_group_member/<%= x.id %>">삭제</a></td>
                </tr>
              </tbody>
            <% end %>
          <% end %>
          </table>
        <% end %>
  
      </div>
    </div>
  </div>
</div>

app/views/small_groups/index.html.erb
 <div class="small-groups-body ">
  <div class="container mt60 mb60">
    
    <div class="align-center mt60 mb50"><h2 class="small-groups-index-h2">소모임</h2></div>
    <% if user_signed_in? %>
   
     <% if current_user.authorization == '2' %>
        <div class=" mb50 align-right"><%= link_to '소모임 만들기', new_small_group_path, {:class => "small-groups-index-new-bttn align-center"} %></div>
     <% else %>
     <%end%>
      
    <% else %>
  
      <div class=" mb50 align-right"><a class = "small-groups-index-new-bttn align-center", href="/users/sign_in">소모임 만들기</a></div>
    <% end %>
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10">
        <div class="row">
          <% if @small_groups.count == 0 %>
            <div class="if-none-contents mt60 mb100 pb100"><p style="font-size: 2rem; font-weight: bold;">소모임이 없습니다.</p></div>
          <% else %>
            <% @small_groups.each do |small_group| %>
              
              
              <div class="col-3">
                <!--<div class="align-center">-->
                <!--  <div class="align-left">-->
                    
                <!--  </div>-->
                <!--</div>-->
                <div class="card dsply-inbl pl05 pr05 ml10 mr10 mb20" style="width: 13rem;">
                  <% if small_group.img_url.to_s == nil || small_group.img_url.to_s == "" %>
                    <div class="align-center"><img class="card-img-top small-groups-index-img overflow-hddn" src="/assets/small_groups/<%= (small_group.id)%13 %>.png" alt="Card image cap"></div>
                  <% elsif %>
                    <div class="align-center"><img class="card-img-top small-groups-index-img overflow-hddn" src="<%=small_group.img_url%>" alt="Card image cap"></div>
                  <% end %>
                  <div class="dropdown-divider"></div>
                  <div class="card-body small-group-p">
                    <div class="align-center"><h5 class="card-title samll-groups-index-title"><%= small_group.group_name %></h5></div>
                    
                    <div class="card-text mb20 ">
                      <p class="small-groups-index-p"><%= small_group.introduce %></p>
                    </div>
                    <div class="align-center">
                      <% if user_signed_in? %>
                        <%= link_to small_group do %>
                          <div class="align-center small-groups-index-more">자세히</div>
                        <% end %>
                      <% else %>
                        <a href="/users/sign_in"><div class="align-center small-groups-index-more">자세히</div></a>
                      <% end %>
                    </div>
                  </div>
                
                    
                </div>
              </div>  
            <% end %>
          <% end %>
         </div> 
        </div>
        <div class="col-1"></div>
      </div>
    </div>
  </div>

app/views/small_groups/my_group.html.erb
<div class="my_club mt60 mb60">
  <div class="container">
    <div class="align-center"><h2 class="myclub-h2">나의 소속</h2></div>
    <div class="row">
      <div class="col-1"></div>
      <div class="col-10 align-center">
        <% if @club_check != nil %>
          <% @small_groups.each do |x| %>
            <% if current_user.id == x.user_id %>
              <a href="/club/club_view/<%= x.club.id %>">    
                <div class="card dsply-inbl pl05 pr05 ml10 mr10 mb20" style="width: 13rem;">
                  <img class="card-img-top" src="/assets/clubs/<%=x.club_id%>.jpg" alt="Club image">
                  <div class="card-body">
                    <h5 class="myclubs-h3"><%= x.club.club_name %></h5>
                    <p class="card-text clubs-p"><%= x.club.introduce %></p>
                  </div>
                </div>
              </a>
            <% end %>
          <% end %>
        <% else %>
            <div class="if-none-contents mt60 mb100 pb100"><p style="font-size: 2rem; font-weight: bold;">가입한 동아리가 없습니다.</p></div>
        <% end %>
      </div>
      <div class="col-1"></div>
    </div>  
  </div>
</div>

app/views/small_groups/new.html.erb
<div class="small-groups-body-1">
  <div class="container pt60 pb60">
    <div class="row">
      <div class="col-3"></div>
      <div class="col-6">
        <div class="small-groups-create-box">
          <div class=""><h3 class="small-groups-create-h3">소모임 만들기</h3></div>
          
          <%= render 'form', small_group: @small_group %>
            
            
        </div>
      </div>
      <div class="col-3"></div>
    </div>
  </div>
</div>

app/views/small_groups/show.html.erb
<div class="small-groups-body-1 mh700">
  <div class="containerpt">
    <div class="row">
      <div class="col-3"></div>
      <div class="col-6">
        <div class="small-groups-show-box">
          <div class="align-center">
            <% if @small_group.img_url.to_s == nil || @small_group.img_url.to_s == "" %>
                <img src="/assets/small_groups/<%= (@small_group.id)%13 %>.png" class="club-view-img mb20 mt20" alt="소모임 이미지">
            <% elsif %>
                <img src="<%= @small_group.img_url%>" class="club-view-img mb20 mt20" alt="소모임 이미지">
            <% end %>
            <div class="dropdown-divider"></div>
            <div class="small-groups-show-title">
              <p>모임 이름</p>
              <h2 class="small-groups-show-h2"><%= @small_group.group_name %></h2>
            </div>
            <div class="small-groups-show-content">
              <p><소개></p>
              <p class="small-groups-show-p"><%= @small_group.introduce %></p>
              
            </div>
             <% if @current_check_option.apply_active == '1' %>
                  <!--로그인 된 상태면 현재 로그인 한 권한에 따라 보이는게 다름-->
                  <% if user_signed_in? %>
                      <!--서버 관리자인 경우-->
                      <% if current_user.authorization == '4' %>
                          <!--현재 로그인 한 단체 관리자가 현재 클럽의 단체 관리자가 아닌경우-->
                          <% if GroupMember.find_by_user_id(current_user.id).small_group_id != @small_group.id  %>
                              
                          <!--현재 로그인 한 단체 관리자가 현재 클럽의 단체 관리자인 경우-->
                          <% else %>
                              <a href="/small_groups/option_change/<%= @small_group.id %>"><div class="club-view-app-btn-3">지원기간 마감</div></a>
                          <% end %>
                      <!--일반 회원인 경우-->
                      <% else %>
                          <!--현재 로그인 한 일반 회원이 클럽에 소속 되어있는 경우,
                          지원 양식이 없는 경우, 클럽에 지원한 적 없는 경우-->
                          <% if @current_check_group != nil && @current_check_group.small_group_id == @small_group.id || SApplyForm.find_by_small_group_id(@small_group.id) == nil %>
                              
                          <!--현재 로그인 한 일반 회원이 클럽에 소속 되어있지 않은 경우-->
                          <% else %>
                              <a href="/s_apply_content/new/<%=@small_group.id%>"><div class="club-view-app-btn-1">지원하기</div></a>
                          <% end %>
                      <% end %>
                  <% else %>
                      <!--로그인이 안되어 있으면 지원하기 버튼을 누르면 로그인 창으로 감.-->
                      <a href="/users/sign_in"><div class="club-view-app-btn-1">지원하기</div></a>
                  <% end %>
              <!--현재 옵션 테이블의 apply_active가 "0"이면 지원할 수 없음-->
              <% else %>
                  <!--현재 로그인한 아이디가 보고있는 클럽에 속해있고 단체 관리자이면 지원을 마감할 수 있음.-->
                  <% if user_signed_in? && current_user.authorization == '0' %>
                      <a href="/small_groups/option_change/<%= @small_group.id %>"><div class="club-view-app-btn-2">지원기간 시작</div></a>
                      <% if ApplyForm.find_by_club_id(@club.id) == nil %>
                      <!--<%# else %>-->
                      <!--    <a href="/apply_form/edit/<%= @club.id %>"><div class="button-in-club-view-yellow">지원서 양식 수정</div></a>-->
                      <% end %>
                      <!--<a href="/apply_content/index"><div class="button-in-club-view-pink">지원 내용 확인</div></a>-->
                  <% elsif user_signed_in? && current_user.authorization == "4" %>
                      <% if @current_check_group != nil && @current_check_group.small_group_id == @small_group.id %>
                          <a href="/small_groups/option_change/<%= @small_group.id %>"><div class="club-view-app-btn-2">지원기간 시작</div></a>
                          <!--<a href="/apply_content/index"><div class="button-in-club-view-pink">지원 내용 확인</div></a>-->
                      <% else %>
                          
                      <% end %>
                  <% else %>
                    
                  <% end %>
              <% end %>
              
            <div class="align-center mb60">
              <%= render partial: "comments/template", locals: {commentable: @small_group, new_comment: @comment} %>
            </div>
          </div> 
        </div>
      </div>
      <div class="col-3"></div>
      </div>
    </div>
  </div>
</div>